Update client
gotify/go-api-client pull request #1
Opened 2019-04-05 15:30 UTC by jmattheis

You can ignore https://github.com/gotify/go-api-client/commit/4321f1f20dbedee2bbefbbd32b38f50e18d5652f

2019-04-05 16:25 UTC, eternal-flame-AD requested changes

2019-04-05 16:25 UTC, eternal-flame-AD commented on Makefile
> +PACKAGE=github.com/gotify/go-api-client/v2
Is this variable used anywhere?

2019-04-05 16:25 UTC, eternal-flame-AD commented on Makefile
> +	wget -O ${SWAGGER} https://github.com/go-swagger/go-swagger/releases/download/v0.19.0/${DOWNLOAD_SWAGGER}
Why not use `go get -u` as we did so in the main repo?

2019-04-05 16:25 UTC, eternal-flame-AD commented on Makefile
>  	${SWAGGER} generate client --help
This always yields a non-zero result, is it used anywhere?

2019-04-05 16:25 UTC, eternal-flame-AD commented on go.mod
> +module github.com/gotify/go-api-client/v2
`go mode tidy` yields a diff on my machine, please update go mod requirements.
```diff
diff --git a/go.mod b/go.mod
index 59a44f9..f7232c7 100644
--- a/go.mod
+++ b/go.mod
@@ -5,6 +5,4 @@ require (
        github.com/go-openapi/runtime v0.17.2
        github.com/go-openapi/strfmt v0.17.0
        github.com/go-openapi/swag v0.17.0
-       github.com/go-openapi/validate v0.17.0
-       golang.org/x/net v0.0.0-20181005035420-146acd28ed58
 )
```

2019-04-05 17:54 UTC, jmattheis commented on Makefile
> +	wget -O ${SWAGGER} https://github.com/go-swagger/go-swagger/releases/download/v0.19.0/${DOWNLOAD_SWAGGER}
I wanted to specify an exact version, I guess when I did this there was a bug in the most recent version.

2019-04-06 12:31 UTC, eternal-flame-AD commented on Makefile
> +	wget -O ${SWAGGER} https://github.com/go-swagger/go-swagger/releases/download/v0.19.0/${DOWNLOAD_SWAGGER}
Okay.

2019-04-06 12:31 UTC, eternal-flame-AD approved these changes

2019-04-06 14:04 UTC, merged